version: '3.7'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - /home/pi/nextcloud-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: always
    networks:
      - nextcloud-net
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8085:80"
    volumes:
      - /home/pi/nextcloud:/var/www/html
      - /media/usbdrive:/data
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    restart: always
    networks:
      - nextcloud-net
networks:
  nextcloud-net:
    driver: bridge
